/* Automatically generated by configure - do not modify */
//#define ARCH_X86 1
#define TUNECPU generic
#define EMULATE_INTTYPES 1
#define EMULATE_FAST_INT 1
#define HAVE_MMX 1
#define __CPU__ 586
#define CONFIG_ENCODERS 1
#define CONFIG_DECODERS 1
#define CONFIG_MPEGAUDIO_HP 1
#define HAVE_W32THREADS 1
#ifndef __MINGW32__
#define __MINGW32__ 1
#endif
#undef  HAVE_MALLOC_H
#undef  HAVE_MEMALIGN
#define SIMPLE_IDCT 1
#define CONFIG_RISKY 1
#define restrict 
